services:
  db:
    image: postgres:15
    container_name: postgres_test_container
    restart: always
    environment:
      POSTGRES_USER: p
      POSTGRES_PASSWORD: p
      POSTGRES_DB: psql_sgbd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
